# remote_theme: pages-themes/merlot@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# - jekyll-feed

# remote_theme: liste-citoyenne-combaillaux/style-modernist
# plugins:
#  - jekyll-remote-theme # add this line to the plugins list if you already have one
#  - jekyll-feed

# lang: fr

# title: Liste citoyenne pour Combaillaux 2026

# header_pages: 
#  - url: programme.html
#    title: Nos ambitions en détail
#  - url: contact.html
#    title: Nous rejoindre
#  - url: collectif.html
#    title: Le collectif
#  - url : cr.html
#    title : Compte-rendus des ateliers


repository: username/liste-citoyenne-combaillaux.github.io

remote_theme: hydecorp/hydejack@v9
plugins:
 - jekyll-remote-theme
 - jekyll-feed
    
# Configuration spécifique à Hydejack
logo: /assets/icons/icon.jpeg
favicon: /assets/icons/favicon.ico
apple_touch_icon: /assets/icons/apple-touch-icon.png

lang: fr

title: Combaillaux Autrement

menu:
 - title: Nos axes de travail
   url: /programme.html
 - title: Le comité de soutien
   url: /collectif.html
 - title: Nous rejoindre
   url: /contact.html
 - title: Documentation
   url: /documents.html
#  - title: Compte-rendus des ateliers
#    url: /cr.html

sidebar:
  social: true  # Make sure this is set to true

author:
  social:
    facebook: https://www.facebook.com/share/14ZXMKa5BjK/?mibextid=wwXIfr

# background image + color
accent_image: /assets/img/fond.png
# accent_color: rgb(237,187,50)
accent_color: 'transparent'


# Add custom CSS
# custom_css: /assets/css/custom.css