repository: username/liste-citoyenne-combaillaux.github.io

remote_theme: hydecorp/hydejack@v9
plugins:
 - jekyll-remote-theme
 - jekyll-feed

hydejack:
  offline:
    enabled: false
  no_sw: true
    
# Configuration spécifique à Hydejack
logo: /assets/icons/icon.jpeg
favicon: /assets/icons/favicon.ico
apple_touch_icon: /assets/icons/apple-touch-icon.png

lang: fr

title: Combaillaux Autrement

menu:
 - title: Nos axes de travail
   url: /programme.html
 - title: Comité de soutien
   url: /collectif.html
 - title: Nous rejoindre
   url: /contact.html
 - title: Documentation
   url: /documentation.html
#  - title: Compte-rendus des ateliers
#    url: /cr.html

sidebar:
  social: true  # Make sure this is set to true

author:
  social:
    facebook: https://www.facebook.com/share/14ZXMKa5BjK/?mibextid=wwXIfr

# background image + color
accent_image: /assets/img/fond.png
# accent_color: rgb(237,187,50)
accent_color: 'transparent'


# Add custom CSS
# custom_css: /assets/css/custom.css